//包名 哪个包下的drl规则文件 只是逻辑上的分类 不是实际意义的
package com.droos.test;

//需要进行规则匹配的对象（ fact ）
import qian.ling.yi.ext.drools.Student;

//规则名称
rule "A"

            //条件Conditions即LHS（left hand side）
            when
                    Student(age<=20);

            //结果Actions即RHS（right hand side或者consequence）
            then
                    System.out.println("我是儿童");
end

rule "B"
            when
                    Student(age>20,age<=30);
            then
                    System.out.println("我是青年人");
end
